# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

model: claude:claude-sonnet-4-20250514
clients:
- type: claude
keybindings: vi
editor: nvim
save_session: true
left_prompt: '>> {color.green}{?session {?agent {agent}>}{session}{?role /}}{!session {?agent {agent}>}}{role}{?rag @{rag}}{color.cyan}{?session )}{!session >}{color.reset} '
