# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

model: claude:claude-3-5-haiku-20241022
clients:
- type: claude
keybindings: vi
editor: nvim
save_session: true
highlight: true
left_prompt: '{color.magenta}======>> {?session {?agent {agent}>}{session}{?role /}}{!session {?agent {agent}>}}{role}{?rag @{rag}}{color.cyan}{?session )}{!session >}{color.reset} '
